development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDISCLOUD_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: everybody_hates_this_production

# On HEROKU run $ heroku addons:create rediscloud:30
