meta_product_name: "Everybody Hates This"
meta_title: "Everybody Hates This - Get your shit together. Together."

meta_description: "We all probably have a lot of things in our life that we know we have to do eventually but we always put off.
Again and again and again. And even though some things are quite important, we just can't get started."

meta_image: "fb_skull.png"
