meta_product_name: "Our product - Everybody Hates This"
meta_title: "About - Everybody Hates This - Get your shit together."
meta_description: "What it is - Everybody Hates This"
meta_image: "skull.png"